version: "3.8"

services:
  showandtell.go:
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/go.Dockerfile
    expose:
      - ${APP_PORT}
    volumes:
      - .:/usr/src/app
    networks:
      - default
    restart: "always"
    command: sh -c "make serve"
  showandtell.nginx:
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - showandtell.go
    ports:
      - "${APP_PORT}:80"
    expose:
      - ${NGINX_PORT}
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
    networks:
      - frontman
      - default
    volumes:
      - ./:/usr/src/app:ro
    restart: "always"

networks:
  frontman:
    external: true
